// © Copyright 2023, LUIC-CIUT's Contributors
export default {
  // english translations
  appInfo: {
    appTitle: `Land Use Impact Calculator`,
    version: `version`,
    lastUpdated: `Last updated`,
    worksheetAttribution: `Generated by the Land Use Impact Calculator (LUIC)`,
  },
  forms: {
    back: `Back`,
    prev: `Previous`,
    next: `Next`,
    skip: `Skip`,
    cancel: `Cancel`,
    reset: `Reset`,
    close: `Close`,
    ok: `Ok`,
    done: `Done`,
    send: `Send`,
    view: `View`,
    edit: `Edit`,
    duplicate: `Duplicate`,
    delete: `Delete`,
    save: `Save`,
    saveToWorksheet: `Save to Worksheet`,
    errorAlert: `Please ensure all required fields are entered correctly.`,
    confirmMsgSent: `Your message has been sent.`,
    confirmDeleteTitle: `Confirm Delete`,
    confirmDeleteMsg: `Are you sure you want to delete the following {item}?`,
    confirmHasBeenDeleted: `{itemType}: {itemName} has been deleted.`,
    servicesEnterZero: `Enter 0 if adding no new facilities`,
    infrastructureEnterZero: `Enter 0 if not constructing new {item}`,
    vktTooltip: `VKT refers to the annual vehicle kilometers travelled`,
    aktTooltip: `AKT refers to the annual active kilometers travelled`,
    fields: {
      email: `Email`,
      name: `Name`,
      message: `Message`,
      quantity: `Quantity`,
      buildingEnergyCode: `Building Energy Code`,
      buildingEnergyCodeShort: `Building Code`,
      eui: `Energy Use Intensity`,
      euiShort: `EUI`,
      energySources: `Energy Sources`,
      energyMix: `Energy Mix`,
      addEnergySource: `Add Energy Source`,
      length: `Length`,
      capitalCostIntensity: `Capital Cost Intensity`,
      capitalCost: `Capital Cost | Capital Costs`,
      maintCostIntensity: `Maintenance Cost Intensity`,
      maintCost: `Maintenance Cost | Maintenance Costs`,
      opAndMaintCost: `Operational & Maintenance Cost`,
      charges: `Charges`,
      taxes: `Taxes`,
      devYear: `Development Year`,
      buildOutYear: `Year of Full Build-out`,
      scenarioTitle: `Scenario Name`,
      scenarioDescription: `Scenario Description`,
      province: `Province`,
      neighbourhoodType: `Neighbourhood Type`,
      numberDwellings: `Number of Dwellings`,
      floorspacePerUnit: `Floorspace Per Unit`,
      floorspaceTotal: `Total Developed Floorspace`,
      annualKT: `Annual kilometers Travelled`,
      totalVKT: `total VKT`,
      puvVKT: `Personal Use Vehicle Kilometers Travelled`,
      transitVKT: `Transit Service Kilometers Travelled`,
      activeKT: `Active Kilometers Travelled`,
      bikeKT: `Active Kilometers Travelled - Bike`,
      walkKT: `Active Kilometers Travelled - Walk`,
      fuelConsumption: `Fuel Consumption`,
    },
    validation: {
      valueNumber: `Value must be a number`,
      value0to100: `Value must be between 0 and 100`,
      valueGreater0: `Value must be greater than 0`,
      energySourcesNone: `Please identify at least 1 energy source.`,
      energySources100: `Please ensure energy sources add up to 100%`,
      requiredField: `{fieldName} is required`,
      fieldNumber: `{fieldName} must be a number`,
      fieldPositive: `{fieldName} must be a positive value`,
      fieldLT100Percent: `{fieldName} must be less than or equal to 100%`,
      fieldGT0Percent: `{fieldName} must be a greater than or equal to 0%`,
      startYearRequired: `Start Year is required`,
      startYearNumber: `Start Year must be a number`,
      startYearInteger: `Start Year must be an integer`,
      startYearRange: `Start Year must be between {startYear} and {endYear}`,
      emailRequired: `Email is required`,
      emailValid: `Must be a valid email address`,
      max50chars: `Max 50 characters`,
    },
  },
  general: {
    email: `email`,
    student: `student`,
    dwelling: `dwelling | dwellings`,
    referencesTitle: `References`,
    referencesNone: `No references listed`,
    percentage: `Percentage`,
    absolute: `Absolute`,
    modified: `Modified`,
    year: `Year`,
    yearAbbr: `yr`,
    total: `total`,
    calculating: `calculating`,
    scenario: `Scenario | Scenarios`,
    title: `title`,
    capital: `Capital`,
    maintenance: `Maintenance`,
  },
  navigation: {
    about: `About`,
    dashboard: `Dashboard`,
    help: `Help`,
    scenario_edit: `Scenario`,
    scenario_view: `Scenario`,
    welcome: `Tutorial`,
  },
  pages: {
    about: {
      title: `About the Land Use Impact Calculator (LUIC) Excel Add-In`,
      betaMsg: `The Land Use Impact Calculator is currently under further development. This version is a Beta release intended for initial testing.`,
      html: `<p>
        The Land Use Impact Calculator (LUIC) is a Microsoft Office Add-In for Excel. It is
        intended to provide municipal decision-makers with a reasonable and
        accurate estimate of the energy consumption and GHG emissions impact
        associated with projects under consideration as part of municipal
        budgeting and capital planning processes.
        </p>`,
      supportedBy: `The Land Use Impact Calculator is supported by:`,
      fcm: `Federation of Canadian Municipalities / Fédération Candaienne des Municipalités`,
      developedBy: `Developed and maintained by:`,
      moreInfo: `For more information or for support contact:`,
    },
    dashboard: {
      myScenarios: `My Scenarios`,
      resizeTitle: `Did you know you can resize?`,
      resizeMsg: `Adjusting the add-in panel a little wider can make it easier to work with.`,
    },
    help: {
      welcomeSlidesBtn: `Tutorial`,
      welcomeSlidesTooltip: `View the tutorial for a quick overview of the Land Use Impact Calculator`,
      feedbackTitle: `Feedback and Bug Reporting`,
      feedbackText: `Have a question, comment or bug report for us? Please send a message using the form below so we can improve the Land Use Impact Calculator.`,
    },
    welcome: {
      title: `Welcome`,
      slide1html: `<p class="text-center">
        The Land Use Impact Calculator provides users with a tool to explore the potential impacts of proposed residential developments
        in terms of GHG emissions produced, infrastructure capital costs incurred, and municipal revenues collected.
        </p>`,
      slide2html: `<p class="text-center">
        Using this Excel add-on, residential development scenarios can be compared. For each scenario, one of six residential neighbourhood development types can be selected from:
        </p>
        <ul class="ml-12">
        <li>Urban infill (high density)</li>
        <li>Urban infill (medium-high density)</li>
        <li>Transit-oriented development (medium-high density)</li>
        <li>Transit-oriented development (low-medium density)</li>
        <li>Low-density (large lot)</li>
        <li>Low-density (small lot)</li>
        </ul>`,
      slide3html: `<p class="text-center">
        Start by defining a proposed development. Users select development parameters and their values. Default values are provided for most parameters, determined by elements like geography and building codes. Users can override the defaults with their own values, if available. For each step of scenario definition, the ⓘ icon provides reference information about default parameters.
        </p>`,
      slide4html: `<p class="text-center">
        When you’ve followed all the steps and defined all parameters values, a worksheet (tab) is created in the current workbook with information about the neighbourhood scenario, including:
        </p>
        <ul class="ml-12 my-4">
        <li>Building mix</li>
        <li>Service Costs</li>
        <li>Infrastructure Costs</li>
        <li>Transportation</li>
        <li>Municipal Costs and Revenues</li>
        <li>Energy Use</li>
        <li>Emissions</li>
        </ul>
        <p class="text-center">
        Each scenario created generates a new worksheet with that scenario’s information.
        </p>`,
      slide5html: `<p class="text-center">
        As multiple scenarios are created, their summary information is added to the Summary worksheet (tab). The graphs on the Summary Graphs worksheet are updated as well. These summary worksheets allow quick scenario comparison.
        </p>`,
      slide6html: `<h2 class="text-center mt-16 pt-8 mx-8">
        That’s it!<br/>
        Let’s get started<br/>
        with your first project!
        </h2>`,
    },
  },
  scenario: {
    workbook: `Workbook`,
    addToWorkbook: `Add this scenario to the current workbook`,
    addToWorkbookShort: `Add to Workbook`,
    updateWorkbook: `Update this scenario in the current workbook`,
    updateWorkbookShort: `Update Workbook`,
    newScenario: `New Scenario`,
    newScenarioTooltiop: `Create a new scenario for estimating energy and emissions impacts.`,
    inputsDefaults: `Inputs/Default Values`,
    outputs: `Outputs`,
    energyUse: `Energy Use`,
    emissions: `Emissions`,
    energyEFs: `Energy Source Emissions Factors`,
    totalDwellings: `Total Dwellings`,
    perDwelling: `Per Dwelling`,
    assumptionsRefs: `Assumptions & References`,
    modules: {
      scenario: `Scenario Info`,
      buildings: `Buildings`,
      buildingsRefs: `Buildings References`,
      services: `Service | Services`,
      servicesRefs: `Services References`,
      servicesCost: `Services Cost`,
      servicesCapCost: `Service Capital Costs`,
      servicesOMCost: `Service Operation and Maintenance`,
      infrastructure: `Infrastructure`,
      infrastructureRefs: `Infrastructure References`,
      infrastructureCost: `Infrastructure Cost`,
      infrastructureCapCost: `Infrastructure Capital Costs`,
      infrastructureOMCost: `Infrastructure Operation and Maintenance`,
      transportation: `Transportation`,
      transportationRefs: `Transportation Assumptions & References`,
      revenue: `Revenue`,
      revenueLong: `Municipal Revenue`,
      revenueTotal: `Total Revenue`,
    },
  },
  appConfig: {
    buildings: {
      homeTypes: {
        single: `Single Detached`,
        row: `Row / Town House`,
        apt: `Apartment`,
      },
      buildingEnergyCodes: {
        Current: `Baseline`,
        CurrentDesc: `Typical average home`,
        passiveHouse: `Passive House`,
        passiveHouseDesc: `Passive house standard`,
        NECB_1: `NECB Tier 2`,
        NECB_1Desc: `National Energy Code of Canada for Buildings Tier 2`,
        NECB_2: `NECB Tier 3`,
        NECB_2Desc: `National Energy Code of Canada for Buildings Tier 3`,
        NECB_3: `NECB Tier 4`,
        NECB_3Desc: `National Energy Code of Canada for Buildings Tier 4`,
        BCStep_2: `BC Step Code Step 2`,
        BCStep_2Desc: `BC Step Code Step 2`,
        BCStep_3: `BC Step Code Step 3`,
        BCStep_3Desc: `BC Step Code Step 3`,
        BCStep_4: `BC Step Code Step 4`,
        BCStep_4Desc: `BC Step Code Step 4`,
        BCStep_5: `BC Step Code Step 5`,
        BCStep_5Desc: `BC Step Code Step 5`,
        TorontoGS_v3T1: `Toronto Green Standard V3 T1`,
        TorontoGS_v3T1Desc: `4-6 Storey Wood Frame MURB, version 3 tier 1`,
        TorontoGS_v3T2: `Toronto Green Standard V3 T2`,
        TorontoGS_v3T2Desc: `4-6 Storey Wood Frame MURB, version 3 tier 1`,
        TorontoGS_v3T3: `Toronto Green Standard V3 T3`,
        TorontoGS_v3T3Desc: `4-6 Storey Wood Frame MURB, version 3 tier 3`,
        TorontoGS_v3T4: `Toronto Green Standard V3 T4`,
        TorontoGS_v3T4Desc: `4-6 Storey Wood Frame MURB, version 3 tier 4`,
      },
      references: {
        description: `Average home sizes are from Shrink That Footprint`,
        cnec: `Canada's National Energy Code`,
        ceud: `Natural Resources Canada Comprehensive Energy Use Database`,
        effImprove25: `25% energy efficiency improvement over Baseline`,
        effImprove50: `50% energy efficiency improvement over Baseline`,
        effImprove60: `60% energy efficiency improvement over Baseline`,
        bcStepCode: `BC Energy Step Code`,
        bcStep2: `No change in energy efficiency improvement over Baseline for part 9 buildings. 20% energy efficiency improvement over Baseline for part 3 buildings`,
        bcStep3: `20% energy efficiency improvement over Baseline for part 9 buildings. 40% energy efficiency improvement over Baseline for part 3 buildings`,
        bcStep4: `40% energy efficiency improvement over Baseline for part 9 buildings. 80% energy efficiency improvement over Baseline for part 3 buildings`,
        bcStep5: `80% energy efficiency improvement over Baseline for part 9 buildings. 80% energy efficiency improvement over Baseline for part 3 buildings`,
        tgs: `Toronto Green Standard`,
        tgsv3t1: `10% energy efficiency improvement over Baseline for multi unit residential buildings`,
        tgsv3t2: `30% energy efficiency improvement over Baseline for multi unit residential buildings`,
        tgsv3t3: `50% energy efficiency improvement over Baseline for multi unit residential buildings`,
        tgsv3t4: `60% energy efficiency improvement over Baseline for multi unit residential buildings`,
        passiveHouse: `International Passive House Association`,
        shrinkThatFootprint: `Home sizes: Shrink That Footprint`,
      },
    },
    regions: {
      provinces: {
        AB: `Alberta`,
        BC: `British Columbia`,
        MB: `Manitoba`,
        NB: `New Brunswick`,
        NL: `Newfoundland and Labrador`,
        NS: `Nova Scotia`,
        NT: `Northwest Territories`,
        NU: `Nunavut`,
        ON: `Ontario`,
        PE: `Prince Edward Island`,
        QC: `Quebec`,
        SK: `Saskatchewan`,
        YT: `Yukon`,
      },
      references: {
        ieso2040: `Derived from IESO 2020 Annual Planning Outlook for 2020 - 2040; held constant past 2040`,
      },
    },
    energySources: {
      energySources: {
        grid: `Grid Electricity`,
        gridDesc: `Grid Electricity`,
        natGas: `Natural Gas`,
        natGasDesc: `Natural Gas`,
        renewableNatGas: `Renewable Natural Gas`,
        renewableNatGasDesc: `Renewable Natural Gas`,
        hydrogen: `Hydrogen`,
        hydrogenDesc: `Hydrogen`,
        gasoline: `Gasoline`,
        gasolineDesc: `Normalized gasoline EFs; contribution of ethanol to blend was removed from these EFs`,
        diesel: `Diesel Fuel Oil`,
        dieselDesc: `Normalized diesel fuel oil EFs; contribution of biodiesel to blend was removed from these EFs`,
        ethanol: `Ethanol`,
        ethanolDesc: `Normalized ethanol EFs; contribution of gasoline to blend was removed from these EFs`,
        biodiesel: `Biodiesel Fuel`,
        biodieselDesc: `Normalized biodiesel EFs; contribution of diesel to blend was removed from these EFs`,
        lightFuelOil: `Light Fuel Oil and Kerosene`,
        lightFuelOilDesc: `Light Fuel Oil and Kerosene`,
        propane: `Propane`,
        propaneDesc: `Propane`,
        heatingOil: `Heating Oil`,
        heatingOilDesc: `Heating Oil`,
        woodWaste: `Wood Waste and Pulping Liquor`,
        woodWasteDesc: `Wood Waste and Pulping Liquor`,
      },
      gwp: {
        description: `GWP values taken from Environment and Climate Change Canada: National Inventory Report (NIR) 1990-2018. Simplified`,
      },
      references: {
        eccNIR2018: `Environment and Climate Change Canada: National Inventory Report (NIR) 1990-2018. Simplified`,
        canESS7: `CanESS V7 model outputs`,
      },
    },
    infrastructure: {
      infrastructureTypes: {
        road2: `Road - 2 Lane`,
        road4: `Road - 4 Lane`,
        sidewalk: `Sidewalk`,
        bikelane: `Bike Lane`,
        water: `Water Pipe`,
        wastewater: `Wastewater Pipe`,
      },
    },
    neighbourhoods: {
      neighbourhoodTypes: {
        urbanInfillV1: `Urban Infill V1`,
        urbanInfillV1Desc: `Med-high housing density, grid road network, mixed-use buildings`,
        urbanInfillV2: `Urban Infill V2`,
        urbanInfillV2Desc: `Med-high housing density, grid road network, mixed-use buildings`,
        TODV1: `Transit Oriented Design V1`,
        TODV1Desc: `Medium housing density at transit node, low-density away from node, mix of grid and closed street network`,
        TODV2: `Transit Oriented Design V2`,
        TODV2Desc: `Medium housing density at transit node, low-density away from node, mix of grid and closed street network`,
        suburbanV1: `Low-density residential V1`,
        suburbanV1Desc: `Closed street network, medium-large lots, stand-alone houses`,
        suburbanV2: `Low-density residential V2`,
        suburbanV2Desc: `Closed street network, medium-large lots, stand-alone houses`,
      },
      devTypes: {
        existing: `existing`,
        greenfield: `greenfield`,
      },
      references: {
        bcClicTool: `BC CLIC tool`,
      },
    },
    revenue: {
      revenueTypes: {
        developmentCharges: `Development Charges`,
        propertyTaxes: `Property Taxes`,
        municipalRevTaxes: `Municipal Revenue Taxes`,
      },
      references: {
        description: `Municipal revenues collected from development cost charges on each new dwelling and annual property taxes. Users can source this information from the municipal property taxes, planning and development, or real estate department, or equivalent.`,
      }
    },
    services: {
      serviceTypes: {
        school: `School`,
        police: `Police`,
        fire: `Fire`,
        waste: `Waste and Recycling`,
      },
      references: {
        description: `All default cost intensities coming from the BC Click tool. Assume no new landfills or trucks need to be purchased by default. For any services, enter 0 if adding no new facilities.`,
      }
    },
    transportation: {
      transportationTypes: {
        puv: `Personal Use Vehicle`,
        transit: `Transit`,
        walk: `Walking`,
        bike: `Biking`,
      },
      references: {
        description: `All default kilometers traveled intensities coming from the Tool for Evaluating Neighbourhood Sustainability developed by NRCAN, CMHC and IBI.
          Fuel consumption values are taken from BC Transit, NREL, and Flemish Institute for Technological Research (VITO)`,
        toolForEvalSust: `Tool for Evaluating Neighbourhood Sustainability`,
        nrelHConsumption: `Hydrogen Fuel Consumption: NREL`,
        vitoNatGasConsumption: `Natural Gas Fuel Consumption: VITO`,
        dieselnetDieselConsumption: `Diesel, Gasoline Fuel Consumption: DieselNet`,
        vktPerYear: `Annual VKT and transit VKT per household: CMHC Greenhouse Gas Emissions From Urban Travel: Tool for Evaluating Neighbourhood Sustainability (2000)`,
      },
      activeMode: `Active Transportation Mode`,
    },
  },
  worksheets: {
    scenariosSummary: `Scenarios Summary`,
    chartsSummary: `Summary Charts`,
  },
};
