// © Copyright 2023, LUIC-CIUT's Contributors
// tree-shaking the fontawesome
// add custom icons as needed to app following this: https://stackoverflow.com/questions/52030435/
// and the vuetify icon font instructions: https://next.vuetifyjs.com/en/features/icon-fonts/

import { fa } from "vuetify/iconsets/fa-svg";
import { library } from "@fortawesome/fontawesome-svg-core"; // Core SVG

// fa free solid imports
import { faCheckCircle, faDotCircle } from "@fortawesome/free-solid-svg-icons";

// fa pro solid imports
import {
  faCaretDown,
  faCaretUp,
  faCircleSmall,
} from "@fortawesome/pro-solid-svg-icons";

// fa regular imports
// import {
// } from "@fortawesome/pro-regular-svg-icons";

// fa pro light imports
import {
  faAirConditioner,
  faAngleLeft,
  faAngleRight,
  faAppleCore,
  faArrowLeft,
  faBars,
  faBenchTree,
  faBicycle,
  faBolt,
  faBuilding,
  faBus,
  faCalculator,
  faCarBolt,
  faCarBuilding,
  faCarBus,
  faChargingStation,
  faChartLineDown,
  faCheck,
  faCheckSquare,
  faChevronLeft,
  faChevronRight,
  faCity,
  faCircle,
  faCircleQuestion,
  faDollarSign,
  faEllipsisV,
  faEnvelope,
  faExclamationTriangle,
  faEye,
  faEyeSlash,
  faFarm,
  faFaucetDrip,
  faFileContract,
  faFireFlameSimple,
  faGalleryThumbnails,
  faGlobe,
  faHammer,
  faHeat,
  faHouse,
  faHouseBuilding,
  faHouseDay,
  faInfoCircle,
  faLightbulb,
  faListUl,
  faLockAlt,
  faKey,
  faMapMarkerAlt,
  faMoneyCheckDollarPen,
  faPersonBiking,
  faPersonWalking,
  faPlus,
  faPump,
  faTimesCircle,
  faTrash,
  faTrees,
  faRecycle,
  faRoad,
  faUser,
  faUsers,
  faSchoolFlag,
  faServer,
  faShareAlt,
  faSmoke,
  faSolarPanel,
  faSquare,
  faSquareParking,
  faSquarePlus,
  faTable,
  faWindTurbine,
} from "@fortawesome/pro-light-svg-icons";

// add all imported icons to library
library.add(
  faEllipsisV,
  faSquare,
  faAirConditioner,
  faAngleLeft,
  faAngleRight,
  faAppleCore,
  faArrowLeft,
  faBars,
  faBenchTree,
  faBicycle,
  faBolt,
  faBuilding,
  faBus,
  faCalculator,
  faCarBolt,
  faCarBuilding,
  faCarBus,
  faCaretDown,
  faCaretUp,
  faChargingStation,
  faChartLineDown,
  faCheck,
  faCheckCircle,
  faCheckSquare,
  faChevronLeft,
  faChevronRight,
  faCircle,
  faCircleQuestion,
  faCircleSmall,
  faCity,
  faDollarSign,
  faDotCircle,
  faEnvelope,
  faExclamationTriangle,
  faEye,
  faEyeSlash,
  faFarm,
  faFaucetDrip,
  faFileContract,
  faFireFlameSimple,
  faGalleryThumbnails,
  faGlobe,
  faHammer,
  faHeat,
  faHouse,
  faHouseBuilding,
  faHouseDay,
  faInfoCircle,
  faLightbulb,
  faListUl,
  faLockAlt,
  faKey,
  faMapMarkerAlt,
  faMoneyCheckDollarPen,
  faPersonBiking,
  faPersonWalking,
  faPlus,
  faPump,
  faRecycle,
  faRoad,
  faSchoolFlag,
  faShareAlt,
  faServer,
  faSmoke,
  faSolarPanel,
  faSquareParking,
  faSquarePlus,
  faTable,
  faTimesCircle,
  faTrash,
  faTrees,
  faUser,
  faUsers,
  faWindTurbine
);

// const aliases = {
//   // ...aliases,
//   city: 'fal fa-city',
// };

const aliases = {
  airConditioner: "fal fa-air-conditioner",
  angleLeft: "fal fa-angle-left",
  angleRight: "fal fa-angle-right",
  appleCore: "fal fa-apple-core",
  arrowLeft: "fal fa-arrow-left",
  bars: "fal fa-bars",
  benchTree: "fal fa-bench-tree",
  bicycle: "fal fa-bicycle",
  bolt: "fal fa-bolt",
  building: "fal fa-building",
  bus: "fal fa-bus",
  calculator: "fal fa-calculator",
  carBolt: "fal fa-car-bolt",
  carBuilding: "fal fa-car-building",
  carBus: "fal fa-car-bus",
  caretDown: "fas fa-caret-down",
  caretUp: "fas fa-caret-up",
  chargingStation: "fal fa-charging-station",
  chartLineDown: "fal fa-chart-line-down",
  check: "fal fa-check",
  checkCircle: "fas fa-check-circle",
  checkSquare: "fal fa-check-square",
  chevronLeft: "fal fa-chevron-left",
  chevronRight: "fal fa-chevron-right",
  circle: "fal fa-circle",
  circleQuestion: "fal fa-circle-question",
  circleSmall: "fas fa-circle-small",
  city: "fal fa-city",
  dollarSign: "fal fa-dollar-sign",
  dotCircle: "fas fa-dot-circle",
  ellipsisV: "fal fa-ellipsis-v",
  envelope: "fal fa-envelope",
  exclamationTriangle: "fal fa-exclamation-triangle",
  eye: "fal fa-eye",
  eyeSlash: "fal fa-eye-slash",
  farm: "fal fa-farm",
  faucetDrip: "fal fa-faucet-drip",
  fileContract: "fal fa-file-contract",
  fireFlameSimple: "fal fa-fire-flame-simple",
  galleryThumbnails: "fal fa-gallery-thumbnails",
  globe: "fal fa-globe",
  hammer: "fal fa-hammer",
  heat: "fal fa-heat",
  house: "fal fa-house",
  houseBuilding: "fal fa-house-building",
  houseDay: "fal fa-house-day",
  infoCircle: "fal fa-info-circle",
  lightbulb: "fal fa-lightbulb",
  listUl: "fal fa-list-ul",
  lockAlt: "fal fa-lock-alt",
  key: "fal fa-key",
  mapMarkerAlt: "fal fa-map-marker-alt",
  moneyCheckDollarPen: "fal fa-money-check-dollar-pen",
  personBiking: "fal fa-person-biking",
  personWalking: "fal fa-person-walking",
  plus: "fal fa-plus",
  pump: "fal fa-pump",
  recycle: "fal fa-recycle",
  road: "fal fa-road",
  schoolFlag: "fal fa-school-flag",
  server: "fal fa-server",
  shareAlt: "fal fa-share-alt",
  smoke: "fal fa-smoke",
  solarPanel: "fal fa-solar-panel",
  square: "fal fa-square",
  squareParking: "fal fa-square-parking",
  squarePlus: "fal fa-square-plus",
  table: "fal fa-table",
  timesCircle: "fal fa-times-circle",
  trash: "fal fa-trash",
  trees: "fal fa-trees",
  user: "fal fa-user",
  users: "fal fa-users",
  windTurbine: "fal fa-wind-turbine",
};

export { aliases, fa };
